### PR TITLE
Increase defense area and goal size

### PR DESCRIPTION
**Pull request by leonardoSCosta**
As pointed out by some teams, the increase in the number of robots (#6 ) might create the possibility to block a large area of the defense and goal area. To avoid that, we are increasing both defense area and goal size. The dimensions were initially increased by 50%, but we are open to any suggestions.

### CODE REVIEW

**Comment by tobiasheineken** [comment]
Any math on the reason why 50% was chosen?

If the field was increased by Factor 2 (which it should have for increasing to 11 robots), a mathematical way should include the goal to scale up to \sqrt(2), increasing by ~40%.

Also, as the game still has one - and only one - keeper, we should be careful when enlarging the goal too much.

**Comment by g3force** [comment]
What's the reason why the field should have been increased by factor 2? I'd me interested in that math as well :)

40% would also be fine for me. That would be 1.68m which could be rounded to 1.7m instead of 1.8m.

The intention with increasing the goal when increasing the defense area is, that the ball has to be shot from a larger distance (but I think that was already clear).

Also, as there are currently quite few goals in the SSL, it is probably not too bad to increase the goal width a bit more.

**Comment by tobiasheineken** [comment]
If our plan from Japan came true, we'd have doubled the whole field again in 2020, resulting in 16 (old) or 4 (new) cameras. That's what this section was about.

If so, we would have increased the playing field by *4 and the number of robots ~*2 - which looks exactly how area and distance should interact: `A = \pi*r*r`

I know why we need to increase the goal. I just wanted to encourage someone to do some math or some experiments, because I have no idea how it plays out.

+40% is also meant for defense area, not only goal itself :)

**Comment by rhololkeolke** [comment]
We definitely have to increase the size to accommodate the additional robots. But we're not doubling the field, so no matter what we do, the relative sizes of the goals/defense area/field are going to be different. So basically its up to us which increase we use (40% vs 50% vs some other number). 

I think we should just accept this pull request as written (i.e. 50% increase). As we don't have any compelling data saying one number is better than the other, and 40% only makes sense in a historical context of the rules. Additionally 40% has the decimal rounding issues Nicolai mentioned.

**Comment by andreaswendler** [comment]
There is a change missing for the definition of the penalty mark, which is still stated to be 1.2 meters from the field lines. While it could be changed to 1.8, I would find it more elegant to remove the number entirely and completely tie it to the defense area size.

**Comment by g3force** [comment]
oh, good catch. However, with #14 the penalty mark is replaced by the the position for one-on-one anyway, when I remember correctly.

**Comment by andreaswendler** [comment]
I ran long simulations against ourselves with the new proposed defense area and goal size and 11 robots and could not find any large detrimental effects. I therefore think that the 50% increase is likely fine (at least for us). It could lead to slightly more goals, but I consider that to be positive.

**Comment by rolfvdhulst** [comment]
I agree with most other comments here.  I do want to make an argument for erring on the larger side of the goals (I think the proposed 50% is good).

Bigger goals tend to reward teams which have more ball possession and will typically reward teams which have an better AI when scoring is easier and increase discrepancies between teams. Whether or not this is a good thing I leave up to you, but in my personal opinion it's a good thing. This will create incentive for teams to work on their AI algorithms and more clearly reward teams for developing good software, which is definitely in line with the league's goals.

Also, it is simply more entertaining to watch games with more goals.

**Pull request merged**
